BKA_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bka.urls')),
]

bka/urls.py
from django.urls import path
from bka import views
 
urlpatterns = [

    path('', views.login_page, name="login_page"),
    
    path('logout_page/', views.logout_page, name="logout_page"),

    path('change_password/', views.change_password, name="change_password"),

    path('add_installation_informations/', views.add_installation_informations, name='add_installation_informations'),

    path('add_validation/', views.add_validation, name='add_validation'),

    path('update_validation/<int:pk>/', views.update_validation, name='update_validation'),

    path('ajax/load-services/', views.load_services, name='ajax_load_services'), # AJAX

    path('cancel_validation/<int:pk>/', views.cancel_validation, name='cancel_validation'),

    path('edit_coordinates/<int:pk>/', views.edit_coordinates, name='edit_coordinates'),

    path('list_coordinates/', views.list_coordinates, name='list_coordinates'),

    path('delete_coordinates/<int:pk>/', views.delete_coordinates, name='delete_coordinates'),

    path('list_coordinates_pmo/', views.list_coordinates_pmo, name='list_coordinates_pmo'),

    path('liste_informations/', views.liste_informations, name='liste_informations'),

    path('liste_infos_valides/', views.liste_infos_valides, name='liste_infos_valides'),

    path('list_valid_informations/', views.list_valid_informations, name='list_valid_informations'),

    path('list_valid_informations_pmo/', views.list_valid_informations_pmo, name='list_valid_informations_pmo'),
]

bka/models.py
from django.db import models

# Create your models here.

class forfait(models.Model):
    nom = models.CharField(max_length=50, null=True)

    def __str__(self):
        return str(self.nom)

class service(models.Model):
    forfait = models.ForeignKey(forfait, null=True, on_delete=models.CASCADE)
    nom_service = models.CharField(max_length=20, null=True)
    nom_produit = models.CharField(max_length=50, null=True)
    debit = models.CharField(max_length=20, null=True)
    volume_jour = models.CharField(max_length=20, null=True)
    volume_nuit = models.CharField(max_length=50, null=True)
    validite = models.CharField(max_length=30, null=True)

    date_ajout = models.DateTimeField(auto_now_add=True)
    date_modif = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.nom_service)
    
class installation_information(models.Model):
    customer = models.CharField(max_length=100, null=True)
    lat = models.FloatField(max_length=20, null=True)
    lon = models.FloatField(max_length=20, null=True)
    status = models.BooleanField(default=False)

    date_ajout = models.DateTimeField(auto_now_add=True)
    date_modif = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.customer) 
    
class validation(models.Model):
    customer = models.ForeignKey(installation_information, null=True, on_delete=models.CASCADE)
    forfait = models.ForeignKey(forfait, null=True, on_delete=models.CASCADE)
    service = models.ForeignKey(service, null=True, on_delete=models.CASCADE)
    activer = models.BooleanField(default=False)

    date_ajout = models.DateTimeField(auto_now_add=True)
    date_modif = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.customer) 

class activation(models.Model):
    information = models.ForeignKey(installation_information, null=True, on_delete=models.CASCADE)
    cle_activation = models.CharField(max_length=100, null=True)

    date_ajout = models.DateTimeField(auto_now_add=True)
    date_modif = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.cle_activation) 
    

bka/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import *

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

class installation_informationForm(forms.ModelForm):
    class Meta:
        model = installation_information
        fields = ['customer', 'lat', 'lon']
        labels = {
            'customer': 'Customer',
            'lat': 'Latitude',
            'lon': 'Longitude',
        }

class validationForm(forms.ModelForm):
    class Meta:
        model = validation
        fields = ['customer', 'forfait', 'service']
        labels = {
            'customer': 'Customer',
            'forfait': 'Forfait',
            'service': 'Service',
        }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['customer'].empty_label = "Choisir"
            self.fields['service'].queryset = service.objects.none()

            if 'forfait' in self.data:
                try:
                    forfait_id = int(self.data.get('forfait'))
                    self.fields['service'].queryset = service.objects.filter(forfait_id=forfait_id).order_by('nom_service')
                except (ValueError, TypeError):
                    pass
            elif self.instance.pk:
                self.fields['service'].queryset = self.instance.forfait.service_set.order_by('nom_service')

class activationForm(forms.ModelForm):
    class Meta:
        model = activation
        fields = '__all__'

class ServiceForm(forms.ModelForm):
    class Meta:
        model = service
        fields = ['nom_service', 'nom_produit', 'debit', 'volume_jour', 'volume_nuit', 'validite']
        labels = {
            'nom_service': 'Nom Service',
            'nom_produit': 'Nom Produit',
            'debit': 'Débit',
            'volume_jour': 'Volume Jour',
            'volume_nuit': 'Volume Nuit',
            'validite': 'Validité',
        }

bka/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import *
from .models import *

from .decorators import *

from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User

import json as JsonResponse

# Create your views here.

@unauthenticated_user
def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('login_page')
        else:
            messages.info(request, "Nom d'utilisateur / mot de passe incorrect !!!")

    context = {}
    return render(request, 'bka/login.html', context)

def logout_page(request):
    logout(request)
    messages.info(request, 'User logout successfuly !!!')
    return redirect('login_page')

def change_password(request, pk):
    try:
        user = User.objects.get(id=pk)
    except User.DoesNotExist:
        user = None

    if request.method == 'POST':
        o_password = request.POST.get('o_password')
        n_password = request.POST.get('n_password')
        cn_password = request.POST.get('cn_password')

    #if user.password == o_password:

@allowed_users(allowed_roles=['tech'])
@login_required(login_url='login_page')
def add_installation_informations(request):
    form = installation_informationForm()
    if request.POST:
        customer = request.POST['customer']
        form = installation_informationForm(request.POST)
        if form.is_valid():
            customer_existing = installation_information.objects.filter(customer=customer) and installation_information.objects.filter(customer=customer).exists
            if customer_existing:
                messages.info(request, 'Cet.te client.e existe déja !!! veuillez réessayer...')
                context = {'form': form}
                return render(request, 'bka/tech/add_installation_informations.html', context)
            else:
                form.save()
                return redirect('/list_coordinates/')

    context = {'form': form}
    return render(request, 'bka/tech/add_installation_informations.html', context)

@allowed_users(allowed_roles=['DG'])
@login_required(login_url='login_page')
def add_validation(request):
    form = validationForm()
    if request.method == 'POST':
        form = validationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/liste_infos_valides/')
    
    context = {'form': form}
    return render(request, 'bka/dg/validations.html', context)

@allowed_users(allowed_roles=['DG'])
@login_required(login_url='login_page')
def update_validation(request, pk):
    try:
        information = installation_information.objects.get(id=pk)
    except installation_information.DoesNotExist:
        information = None

    try:
        validations = validation.objects.get(id=pk)
    except validation.DoesNotExist:
        validations = None 
    
    if information.customer == validation.customer:
        information.status = True

        form = validationForm(instance=validations)
        if request.method == 'POST':
            form = validationForm(request.POST, instance=validations)
            if form.is_valid():
                form.save()
                validations.save(update_fields=['status'])
                return redirect('/liste_infos_valides/')
    
    context = {'form': form}
    return render(request, 'bka/dg/validations.html', context)

@allowed_users(allowed_roles=['DG'])
@login_required(login_url='login_page')
def load_services(request):
    forfait_id = request.GET.get('forfait_id')
    services = service.objects.filter(forfait_id=forfait_id).all()
    context = {'services': services}
    return render(request, 'bka/dg/services_dropdown_list_options.html', context)
    
@allowed_users(allowed_roles=['DG'])
@login_required(login_url='login_page')
def cancel_validation(request, pk):
    try:
        information = installation_information.objects.get(id=pk)
    except installation_information.DoesNotExist:
        information = None

    if information.status == True:
        if request.method == "POST":
            information.status = False
            information.save(update_fields=['status'])
            return redirect('/liste_informations/')

    context = {'item': information}
    return render(request, 'bka/dg/cancel_validation.html', context)

@allowed_users(allowed_roles=['tech'])
@login_required(login_url='login_page')
def edit_coordinates(request, pk):
    try:
        information = installation_information.objects.get(id=pk)
    except installation_information.DoesNotExist:
        information = None

    if information.status == False:
        form = installation_informationForm(instance=information)
        if request.method == 'POST':
            customer = request.POST['customer']
            form = installation_informationForm(request.POST, instance=information)
            if form.is_valid():
                customer_existing = installation_information.objects.filter(customer=customer) and installation_information.objects.filter(customer=customer).exists
                if customer_existing:
                    messages.info(request, 'Cet.te client.e existe déja !!! veuillez réessayer...')
                    context = {'form': form}
                    return render(request, 'bka/tech/edit_coordinates.html', context)
                else:
                    form.save()
                    return redirect('/list_coordinates/')
        
    context = {'form': form}
    return render(request, 'bka/tech/edit_coordinates.html', context)

@allowed_users(allowed_roles=['tech'])
@login_required(login_url='login_page')
def delete_coordinates(request, pk):
    coordinates = installation_information.objects.get(id=pk)
    if coordinates.status == False:
        if request.method == "POST":
            coordinates.delete()
            return redirect('/list_coordinates/')
    
    context = {'item': coordinates}
    return render(request, 'bka/tech/delete_validation.html', context)

@allowed_users(allowed_roles=['tech'])
@login_required(login_url='login_page')
def list_coordinates(request):
    try:
        list_information = installation_information.objects.all().filter(status=False)
    except installation_information.DoesNotExist:
        list_information = None

    context = {'list': list_information}
    return render(request, 'bka/tech/list_coordinates.html', context)

@allowed_users(allowed_roles=['PMO'])
@login_required(login_url='login_page')
def list_coordinates_pmo(request):
    try:
        list_information = installation_information.objects.all().filter(status=False)
    except installation_information.DoesNotExist:
        list_information = None

    context = {'list': list_information}
    return render(request, 'bka/pmo/list_coordinates_pmo.html', context)

@allowed_users(allowed_roles=['DG'])
@login_required(login_url='login_page')
def liste_informations(request):
    try:
        list_information = installation_information.objects.all()
    except installation_information.DoesNotExist:
        list_information = None

    context = {'list': list_information}
    return render(request, 'bka/dg/liste_informations.html', context)

@allowed_users(allowed_roles=['DG'])
@login_required(login_url='login_page')
def liste_infos_valides(request):
    try:
        list_informations = installation_information.objects.all()
    except installation_information.DoesNotExist:
        list_informations = None

    try:
        list_informations_valides = validation.objects.all()
    except validation.DoesNotExist:
        list_informations_valides = None

    context = {'list_infos': list_informations, 'list_infos_valides': list_informations_valides}
    return render(request, 'bka/dg/liste_infos_valides.html', context)

@allowed_users(allowed_roles=['PMO'])
@login_required(login_url='login_page')
def list_valid_informations_pmo(request):
    try:
        list_valid_information = installation_information.objects.all().filter(status=True)
    except installation_information.DoesNotExist:
        list_valid_information = None

    context = {'list': list_valid_information}
    return render(request, 'bka/pmo/list_valid_informations_pmo.html', context)

@allowed_users(allowed_roles=['tech'])
@login_required(login_url='login_page')
def list_valid_informations(request):
    try:
        list_valid_information = installation_information.objects.all().filter(status=True)
    except installation_information.DoesNotExist:
        list_valid_information = None

    context = {'list': list_valid_information}
    return render(request, 'bka/tech/list_valid_informations.html', context)

bka/templates/bka/dg/cancel_validation.html
{% extends 'bka/dg/main_dg.html' %}

{% block content %}

<form action="{% url 'cancel_validation' item.id %}" method="POST">

    {% csrf_token %}

    <br>
 
    <div class="row">
        <div class="container col-md-6">
            <div class="card text-white bg-secondary mb-3">
                <div class="card-header">Annuler la validation</div>
                <div class="card-body">

                    <strong><p>Etes vous sure de vouloir annuler la validation de "{{item}}" ?</p></strong>

                    <div>

                        <a class="btn btn-warning btn-sm" href="{% url 'list_all_informations' %}">Cancel</a>

                        <input class="btn btn-danger btn-sm" type="submit" name="confirm">

                    </div>

                </div>
            </div>
        </div>
    </div>

</form>

{% endblock %}

bka/templates/bka/dg/list_all_informations.html
{% extends 'bka/dg/main_dg.html' %}

{% block content %}

<br>

<div class="row">
    <div class="container col-md-10">
        <div class="card text-white bg-secondary mb-3">
            <div class="card-header">Liste des informations</div>
            <div class="card-body">
            <table class="table table-sm">
                <tr>
                    <th></th>
                    <th>Client</th>
                    <th>Latitude</th>
                    <th>Longitude</th>
                    <th>Forfait</th>
                    <th>Service</th>
                    <th></th>
                </tr>

                {% for l in list %}
                    <tr>
                        <th></th>
                        <th>{{ l.customer }}</th>
                        <th>{{ l.lat }}</th>
                        <th>{{ l.lon }}</th>
                        <th>{{ l.forfait }}</th>
                        <th>{{ l.service }}</th>

                        {% if l.status == False %}
                            <th><a class="btn btn-outline-light btn-sm" style="width: 80%;" href="{% url 'validation_installation_informations' l.id %}">Validation</a></th>
                        {% endif %}

                        {% if l.status == True %}
                            <th><a class="btn btn-outline-warning btn-sm" style="width: 80%;" href="{% url 'cancel_validation' l.id %}">Annuler validation</a></th>
                        {% endif %}

                    </tr>
                {% endfor %}
            </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

bka/templates/bka/dg/list_validations.html
{% extends 'bka/dg/main_dg.html' %}

{% load crispy_forms_tags %}
{% block content %}

<br>

<div class="row">
    <div class="container col-md-4">
        <div class="card text-white bg-secondary mb-3">
            <div class="card-header" style="color: gold;">Liste des informations non validées</div>
            <div class="card-body">
            <table class="table table-sm">
                <tr>
                    <th></th>
                    <th>Client</th>
                    <th>Latitude</th>
                    <th>Longitude</th>
                    <th></th>
                </tr>

                {% for l in list %}
                    <tr>

                            <th></th>
                            <th>{{ l.customer }}</th>
                            <th>{{ l.lat }}</th>
                            <th>{{ l.lon }}</th>

                    </tr>
                {% endfor %}
            </table>
            </div>
        </div>
    </div>

    <div class="container col-md-6">
        <div class="card text-white bg-secondary mb-3">
            <div class="card-header" style="color: chartreuse;">Liste des informations validées</div>
            <div class="card-body">
            <table class="table table-sm">
                <tr>
                    <th></th>
                    <th>Client</th>
                    <th>Latitude</th>
                    <th>Longitude</th>
                    <th>Forfait</th>
                    <th>Service</th>
                    <th></th>
                </tr>

                {% for l in list %}
                    <tr>
                        {% if l.status == True %}

                            <th></th>
                            <th>{{ l.customer }}</th>
                            <th>{{ l.lat }}</th>
                            <th>{{ l.lon }}</th>
                            <!-- <th>{{ l.forfait }}</th>
                            <th>{{ l.service }}</th> -->

                            {% if l.status == True %}
                                <th><a class="btn btn-outline-warning btn-sm" style="width: 80%;" href="{% url 'cancel_validation' l.id %}">Annuler validation</a></th>
                            {% endif %}

                        {% endif %}

                    </tr>
                {% endfor %}
            </table>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="container col-md-4">
        <div class="card text-white bg-secondary mb-3">
            <div class="card-header">Validation informations</div>
            <div class="card-body">

                <form method="POST" id="validationForm" data-services-url="{% url 'ajax_load_services' %}">
            
                    {% csrf_token %}
    
                    {% for message in messages %}
                        <p style="color: yellowgreen; text-align: center;" id="messages">{{ message }}</p>
                    {% endfor %}
                    
                    {{ form.as_p }}
    
                    <button class="btn btn-sm btn-light" type="submit" name="submit">
                        valider formulaire
                    </button>
                    
                </form>

                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
                <script>
                    $("#id_forfait").change(function () {
                        const url = $("#validationForm").attr("data-services-url");  // get the url of the `load_cities` view
                        const forfaitId = $(this).val();  // get the selected country ID from the HTML input

                        $.ajax({                       // initialize an AJAX request
                            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                            data: {
                                'forfait_id': forfaitId       // add the country id to the GET parameters
                            },
                            success: function (data) {   // `data` is the return of the `load_cities` view function
                                $("#id_service").html(data);  // replace the contents of the city input with the data that came from the server
                                /*

                                let html_data = '<option value="">---------</option>';
                                data.forEach(function (city) {
                                    html_data += `<option value="${city.id}">${city.name}</option>`
                                });
                                console.log(html_data);
                                $("#id_city").html(html_data);

                                */
                            }
                        });

                    });
                </script>

            </div>
        </div>
    </div>
</div>

{% endblock %}

bka/templates/bka/dg/liste_informations.html
{% extends 'bka/dg/main_dg.html' %}

{% load crispy_forms_tags %}
{% block content %}

<br>

<div class="row">
    <div class="container col-md-6">
        <div class="card text-white bg-secondary mb-3">
            <div class="card-header" style="color: gold;">Liste des informations non validées</div>
            <div class="card-body">
            <table class="table table-sm">
                <tr>
                    <th></th>
                    <th>Client</th>
                    <th>Latitude</th>
                    <th>Longitude</th>
                    <th></th>
                </tr>

                {% for l in list %}
                    <tr>
                        {% if l.status == False %}

                            <th></th>
                            <th>{{ l.customer }}</th>
                            <th>{{ l.lat }}</th>
                            <th>{{ l.lon }}</th>

                        {% endif %}

                    </tr>
                {% endfor %}
            </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

bka/templates/bka/dg/liste_infos_valides.html
{% extends 'bka/dg/main_dg.html' %}

{% load crispy_forms_tags %}
{% block content %}

<br>

<div class="row">
    <div class="container col-md-6">
        <div class="card text-white bg-secondary mb-3">
            <div class="card-header" style="color: chartreuse;">Liste des informations validées</div>
            <div class="card-body">
            <table class="table table-sm">
                <tr>
                    <th></th>
                    <th>Client</th>
                    <!-- <th>Latitude</th>
                    <th>Longitude</th> -->
                    <th>Forfait</th>
                    <th>Service</th>
                    <th></th>
                </tr>

                {% for l in list_infos_valides %}
                    <tr>
                            <th></th>
                            <th>{{ l.customer }}</th>
                            <!-- <th>{{ l.lat }}</th>
                            <th>{{ l.lon }}</th> -->
                            <th>{{ l.forfait }}</th>
                            <th>{{ l.service }}</th>

                            {% if l.status == True %}
                                <th><a class="btn btn-outline-warning btn-sm" style="width: 80%;" href="{% url 'cancel_validation' l.id %}">Annuler validation</a></th>
                            {% endif %}

                    </tr>
                {% endfor %}
            </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

bka/templates/bka/dg/main_dg.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>BKA</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">

</head>
<body>

    {% include 'bka/dg/navbar_dg.html' %}
   
    <div class="container-fluid">

    {% block content %}




    {% endblock %}

    </div>

    <hr>
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" 
integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" 
integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
crossorigin="anonymous"></script>



</html>

bka/templates/bka/dg/navbar_dg.html
{% load static %}

<style>
    .hello-msg{
        font-size: 18px;
        color: white;
        margin-right: 20px;
    }

    .href{
        font-size: 18px;
        color: yellow;
        margin-right: 20px;
    }

</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <img style="height: 50px; width: 140px;" src="{% static 'images/logo.png' %}">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">

            <li class="nav-item active">
                <a class="nav-link" href="{% url 'liste_informations' %}">Informations non validées |</a>
            </li>

            <li class="nav-item active">
                <a class="nav-link" href="{% url 'add_validation' %}">Validation informations |</a>
            </li>

            <li class="nav-item active">
                <a class="nav-link" href="{% url 'liste_infos_valides' %}">Informations validées |</a>
            </li>
            
        </ul>
    </div>

    <span class="hello-msg">{{ request.user }}</span>&nbsp;
    <span><a class="href" href="{% url 'logout_page' %}">logout</a></span>

</nav>

bka/templates/bka/dg/validation_installation_informations.html
{% extends 'bka/dg/main_dg.html' %}

{% load crispy_forms_tags %}
{% block content %}

<br>

<div class="row">
    <div class="container col-md-6">
        <div class="card text-white bg-secondary mb-3">
            <div class="card-header">Formulaire de validation</div>
            <div class="card-body">

                <form method="POST" id="validationForm" data-services-url="{% url 'ajax_load_services' %}">
            
                {% csrf_token %}
                
                {{ form.as_p }}

                <button class="btn btn-light" type="submit" name="submit">
                    valider formulaire
                </button>

                </form>

            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

<script>
    $("#id_forfait").change(function () {
        const url = $("#validationForm").attr("data-services-url");  // get the url of the `load_cities` view
        const forfaitId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'forfait_id': forfaitId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_service").html(data);  // replace the contents of the city input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);

                */
            }
        });

    });
</script>

{% endblock %}

bka/templates/bka/dg/validations.html
{% extends 'bka/dg/main_dg.html' %}

{% load crispy_forms_tags %}
{% block content %}

<br>

<div class="row">
    <div class="container col-md-6">
        <div class="card text-white bg-secondary mb-3">
            <div class="card-header">Formulaire de validation</div>
            <div class="card-body">

                <form method="post" id="validationForm" data-services-url="{% url 'ajax_load_services' %}">
            
                {% csrf_token %}
                
                {{ form.as_p }}

                <button class="btn btn-light" type="submit" value="Submit">
                    valider formulaire
                </button>

                </form>

            </div>
        </div>
    </div>
</div>

<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script> -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_forfait").change(function () {
        const url = $("#validationForm").attr("data-services-url");  // get the url of the `load_cities` view
        const forfaitId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'forfait_id': forfaitId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_service").html(data);  // replace the contents of the city input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (service) {
                    html_data += `<option value="${service.id}">${service.nom_service}</option>`
                });
                console.log(html_data);
                $("#id_service").html(html_data);

                */
            }
        });

    });
</script>

{% endblock %}